[2023-03-29T08:41:40.537+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: docker_sample.docker_op_tester scheduled__2023-03-28T20:20:00+00:00 [queued]>
[2023-03-29T08:41:40.544+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: docker_sample.docker_op_tester scheduled__2023-03-28T20:20:00+00:00 [queued]>
[2023-03-29T08:41:40.544+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-03-29T08:41:40.545+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2023-03-29T08:41:40.545+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-03-29T08:41:40.570+0000] {taskinstance.py:1304} INFO - Executing <Task(DockerOperator): docker_op_tester> on 2023-03-28 20:20:00+00:00
[2023-03-29T08:41:40.574+0000] {standard_task_runner.py:55} INFO - Started process 156929 to run task
[2023-03-29T08:41:40.578+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'docker_sample', 'docker_op_tester', 'scheduled__2023-03-28T20:20:00+00:00', '--job-id', '1219', '--raw', '--subdir', 'DAGS_FOLDER/test_docker_operator.py', '--cfg-path', '/tmp/tmp6zzlfss_']
[2023-03-29T08:41:40.582+0000] {standard_task_runner.py:83} INFO - Job 1219: Subtask docker_op_tester
[2023-03-29T08:41:40.654+0000] {task_command.py:389} INFO - Running <TaskInstance: docker_sample.docker_op_tester scheduled__2023-03-28T20:20:00+00:00 [running]> on host vibrdairflow.tciw5gv3lhjetcyg0kqzfvdylc.hx.internal.cloudapp.net
[2023-03-29T08:41:40.774+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=docker_sample
AIRFLOW_CTX_TASK_ID=docker_op_tester
AIRFLOW_CTX_EXECUTION_DATE=2023-03-28T20:20:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-28T20:20:00+00:00
[2023-03-29T08:41:40.784+0000] {docker.py:306} INFO - Starting docker container from image centos:latest
[2023-03-29T08:41:40.789+0000] {docker.py:314} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2023-03-29T08:41:42.148+0000] {docker.py:373} INFO - TEST DOCKER SUCCESSFUL
[2023-03-29T08:41:43.067+0000] {taskinstance.py:1322} INFO - Marking task as SUCCESS. dag_id=docker_sample, task_id=docker_op_tester, execution_date=20230328T202000, start_date=20230329T084140, end_date=20230329T084143
[2023-03-29T08:41:43.124+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2023-03-29T08:41:43.146+0000] {taskinstance.py:2582} INFO - 1 downstream tasks scheduled from follow-on schedule check
