[2023-03-29T08:46:31.858+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: docker_sample.docker_op_tester scheduled__2023-03-28T22:50:00+00:00 [queued]>
[2023-03-29T08:46:31.864+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: docker_sample.docker_op_tester scheduled__2023-03-28T22:50:00+00:00 [queued]>
[2023-03-29T08:46:31.865+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-03-29T08:46:31.865+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2023-03-29T08:46:31.865+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-03-29T08:46:31.892+0000] {taskinstance.py:1304} INFO - Executing <Task(DockerOperator): docker_op_tester> on 2023-03-28 22:50:00+00:00
[2023-03-29T08:46:31.896+0000] {standard_task_runner.py:55} INFO - Started process 166857 to run task
[2023-03-29T08:46:31.903+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'docker_sample', 'docker_op_tester', 'scheduled__2023-03-28T22:50:00+00:00', '--job-id', '1281', '--raw', '--subdir', 'DAGS_FOLDER/test_docker_operator.py', '--cfg-path', '/tmp/tmpd74oqj97']
[2023-03-29T08:46:31.905+0000] {standard_task_runner.py:83} INFO - Job 1281: Subtask docker_op_tester
[2023-03-29T08:46:31.968+0000] {task_command.py:389} INFO - Running <TaskInstance: docker_sample.docker_op_tester scheduled__2023-03-28T22:50:00+00:00 [running]> on host vibrdairflow.tciw5gv3lhjetcyg0kqzfvdylc.hx.internal.cloudapp.net
[2023-03-29T08:46:32.059+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=docker_sample
AIRFLOW_CTX_TASK_ID=docker_op_tester
AIRFLOW_CTX_EXECUTION_DATE=2023-03-28T22:50:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-28T22:50:00+00:00
[2023-03-29T08:46:32.068+0000] {docker.py:306} INFO - Starting docker container from image centos:latest
[2023-03-29T08:46:32.073+0000] {docker.py:314} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2023-03-29T08:46:33.120+0000] {docker.py:373} INFO - TEST DOCKER SUCCESSFUL
[2023-03-29T08:46:33.709+0000] {taskinstance.py:1322} INFO - Marking task as SUCCESS. dag_id=docker_sample, task_id=docker_op_tester, execution_date=20230328T225000, start_date=20230329T084631, end_date=20230329T084633
[2023-03-29T08:46:33.759+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2023-03-29T08:46:33.777+0000] {taskinstance.py:2582} INFO - 1 downstream tasks scheduled from follow-on schedule check
